// Dữ liệu khoa học & ý nghĩa Triết học Mác - Lênin (MLN111) của các hành tinh trong Hệ Mặt Trời
export const PLANETS = [
  {
    id: 'sun',
    name: 'Mặt Trời',
    latinName: 'Sol / Sun',
    type: 'Sao lùn vàng (G2V)',
    color: '#FFB830',
    emissive: '#FF9100',
    size: 2.8,
    orbitRadius: 0,
    orbitSpeed: 0,
    rotationSpeed: 0.1,
    facts: {
      diameter: '1.392.700 km (gấp 109 lần Trái Đất)',
      mass: 'Chiếm 99.86% khối lượng toàn Hệ Mặt Trời',
      temp: '5.500°C (bề mặt) · 15 triệu °C (lõi)',
      distance: '0 km (Trung tâm hệ)',
    },
    philosophy: {
      concept: 'Nguồn năng lượng vật chất & Sự chuyển hóa',
      quote: 'Vận động là phương thức tồn tại của vật chất, là thuộc tính cố hữu của vật chất.',
      author: 'Ph.Ăng-ghen (Biện chứng của tự nhiên)',
      analysis:
        'Phản ứng nhiệt hạch trong lòng Mặt Trời liên tục biến đổi hydro thành heli, tỏa ra bức xạ nuôi dưỡng sự sống. Đây là minh chứng hùng hồn cho quy luật bảo toàn và chuyển hóa năng lượng — vật chất không tự sinh ra và không mất đi, chỉ chuyển từ dạng này sang dạng khác.',
    },
  },
  {
    id: 'mercury',
    name: 'Sao Thủy',
    latinName: 'Mercury',
    type: 'Hành tinh đất đá',
    color: '#A09B93',
    size: 0.45,
    orbitRadius: 5.5,
    orbitSpeed: 0.88,
    rotationSpeed: 0.2,
    facts: {
      diameter: '4.879 km',
      distance: '57,9 triệu km từ Mặt Trời',
      orbitalPeriod: '88 ngày Trái Đất',
      temp: '-180°C đến +430°C',
    },
    philosophy: {
      concept: 'Quy luật Thống nhất & Đấu tranh giữa các mặt đối lập',
      quote: 'Sự phát triển là cuộc đấu tranh giữa các mặt đối lập.',
      author: 'V.I. Lênin',
      analysis:
        'Với một mặt thiêu đốt 430°C và mặt kia đóng băng -180°C do không có khí quyển điều hòa, Sao Thủy là hình mẫu tự nhiên sinh động của mâu thuẫn biện chứng — hai trạng thái đối lập gay gắt cùng tồn tại trong một chỉnh thể thống nhất.',
    },
  },
  {
    id: 'venus',
    name: 'Sao Kim',
    latinName: 'Venus',
    type: 'Hành tinh đất đá',
    color: '#E8C587',
    atmosphereColor: '#F5DEB3',
    size: 0.85,
    orbitRadius: 8.5,
    orbitSpeed: 0.65,
    rotationSpeed: -0.15, // quay nghịch hành
    facts: {
      diameter: '12.104 km',
      distance: '108,2 triệu km từ Mặt Trời',
      orbitalPeriod: '225 ngày Trái Đất',
      temp: '~465°C (Hành tinh nóng nhất)',
    },
    philosophy: {
      concept: 'Quy luật Lượng đổi dẫn đến Chất đổi',
      quote: 'Những thay đổi thuần túy về lượng khi đạt đến một giới hạn nhất định sẽ chuyển hóa thành sự khác nhau về chất.',
      author: 'Ph.Ăng-ghen',
      analysis:
        'Sự tích tụ liên tục của khí carbon dioxide (CO2) qua hàng trăm triệu năm đã vượt qua "điểm nút", gây ra hiệu ứng nhà kính mất kiểm soát, biến một hành tinh từng có nước thành một "lò lửa" khắc nghiệt. Đó là ví dụ điển hình về bước nhảy vọt làm thay đổi căn bản chất lượng của tự nhiên.',
    },
  },
  {
    id: 'earth',
    name: 'Trái Đất',
    latinName: 'Terra / Earth',
    type: 'Hành tinh sự sống',
    color: '#2B82C9',
    landColor: '#589A42',
    size: 0.95,
    orbitRadius: 12.0,
    orbitSpeed: 0.5,
    rotationSpeed: 0.45,
    tilt: 0.41, // 23.5 độ
    hasMoon: true,
    facts: {
      diameter: '12.742 km',
      distance: '149,6 triệu km (1 AU)',
      orbitalPeriod: '365,25 ngày',
      temp: 'Trung bình 15°C',
    },
    philosophy: {
      concept: 'Hình thức vận động xã hội — Đỉnh cao của vật chất',
      quote: 'Ý thức không bao giờ có thể là cái gì khác hơn là sự tồn tại được ý thức.',
      author: 'C.Mác & Ph.Ăng-ghen (Hệ tư tưởng Đức)',
      analysis:
        'Trên Trái Đất, vật chất đã tiến hóa từ vận động cơ học, vật lý, hóa học, sinh học đến đỉnh cao là hình thức vận động XÃ HỘI với sự xuất hiện của con người. Con người cải tạo tự nhiên thông qua hoạt động thực tiễn có ý thức, khẳng định thế giới quan duy vật lịch sử.',
    },
  },
  {
    id: 'mars',
    name: 'Sao Hỏa',
    latinName: 'Mars',
    type: 'Hành tinh đỏ',
    color: '#D15838',
    size: 0.6,
    orbitRadius: 15.5,
    orbitSpeed: 0.4,
    rotationSpeed: 0.42,
    tilt: 0.44,
    facts: {
      diameter: '6.779 km',
      distance: '227,9 triệu km từ Mặt Trời',
      orbitalPeriod: '687 ngày Trái Đất',
      temp: '-140°C đến +20°C',
    },
    philosophy: {
      concept: 'Cặp phạm trù Khả năng & Hiện thực',
      quote: 'Hiện thực là cái đã có, khả năng là cái chưa có nhưng sẽ tới khi đủ điều kiện.',
      author: 'Triết học Mác - Lênin',
      analysis:
        'Sao Hỏa từng có nước dạng lỏng và nay mở ra "khả năng" định cư cho nhân loại trong tương lai. Để biến khả năng thành hiện thực, con người phải nắm bắt quy luật khách quan và phát triển lực lượng sản xuất khoa học kỹ thuật thông qua thực tiễn.',
    },
  },
  {
    id: 'jupiter',
    name: 'Sao Mộc',
    latinName: 'Jupiter',
    type: 'Khí khổng lồ',
    color: '#C69466',
    bands: true,
    size: 1.85,
    orbitRadius: 20.5,
    orbitSpeed: 0.28,
    rotationSpeed: 0.8,
    facts: {
      diameter: '139.820 km (gấp 11 lần Trái Đất)',
      distance: '778,5 triệu km từ Mặt Trời',
      orbitalPeriod: '11,86 năm Trái Đất',
      temp: '-110°C (tầng mây)',
    },
    philosophy: {
      concept: 'Mối liên hệ phổ biến trong Vũ trụ',
      quote: 'Toàn bộ giới tự nhiên hữu cơ là một bằng chứng về tính thống nhất của các mặt đối lập.',
      author: 'Ph.Ăng-ghen',
      analysis:
        'Sao Mộc với trường hấp dẫn cực mạnh hoạt động như một "máy hút bụi" của Hệ Mặt Trời, hút hầu hết thiên thạch và sao chổi đe dọa Trái Đất. Đây là minh chứng rõ nét cho nguyên lý mối liên hệ phổ biến: các sự vật, hiện tượng trong vũ trụ không tồn tại cô lập mà luôn tác động, ràng buộc lẫn nhau.',
    },
  },
  {
    id: 'saturn',
    name: 'Sao Thổ',
    latinName: 'Saturn',
    type: 'Khí khổng lồ có vành đai',
    color: '#E0CB9B',
    hasRings: true,
    ringInner: 2.2,
    ringOuter: 3.8,
    size: 1.55,
    orbitRadius: 26.0,
    orbitSpeed: 0.2,
    rotationSpeed: 0.75,
    tilt: 0.47,
    facts: {
      diameter: '116.460 km',
      distance: '1,43 tỷ km từ Mặt Trời',
      orbitalPeriod: '29,45 năm Trái Đất',
      temp: '-140°C',
    },
    philosophy: {
      concept: 'Cặp phạm trù Bản chất & Hiện tượng',
      quote: 'Nếu hình thái biểu hiện và bản chất của sự vật trực tiếp đồng nhất với nhau, thì mọi khoa học sẽ trở thành thừa.',
      author: 'C.Mác (Tư bản, tập III)',
      analysis:
        'Hiện tượng bên ngoài là một dải vành đai rắn đặc tuyệt đẹp phát sáng; nhưng bản chất bên trong được khoa học khám phá lại là hàng tỷ mảnh băng đá và bụi quay với tốc độ khác nhau. Nhận thức khoa học đi từ hiện tượng phong phú bên ngoài để nắm bắt bản chất quy luật bên trong.',
    },
  },
  {
    id: 'uranus',
    name: 'Sao Thiên Vương',
    latinName: 'Uranus',
    type: 'Băng khổng lồ',
    color: '#82C8D2',
    hasRings: true,
    ringInner: 1.8,
    ringOuter: 2.4,
    size: 1.15,
    orbitRadius: 31.0,
    orbitSpeed: 0.14,
    rotationSpeed: -0.3,
    tilt: 1.71, // nghiêng 98 độ
    facts: {
      diameter: '50.724 km',
      distance: '2,87 tỷ km từ Mặt Trời',
      orbitalPeriod: '84 năm Trái Đất',
      temp: '-224°C (Khí quyển lạnh nhất)',
    },
    philosophy: {
      concept: 'Tính đa dạng của các dạng thức tồn tại vật chất',
      quote: 'Vật chất là vô cùng, vô tận; tính đa dạng của nó là thiên hình vạn trạng.',
      author: 'V.I. Lênin',
      analysis:
        'Trục quay nằm ngang gần như vuông góc với mặt phẳng quỹ đạo (98 độ) khiến Sao Thiên Vương lăn trên quỹ đạo. Điều này chứng minh quy luật chuyển động của vật chất không rập khuôn đơn điệu mà biểu hiện muôn hình vạn trạng theo những điều kiện lịch sử - tự nhiên cụ thể.',
    },
  },
  {
    id: 'neptune',
    name: 'Sao Hải Vương',
    latinName: 'Neptune',
    type: 'Băng khổng lồ xanh thẳm',
    color: '#3466CA',
    size: 1.1,
    orbitRadius: 36.0,
    orbitSpeed: 0.1,
    rotationSpeed: 0.35,
    tilt: 0.5,
    facts: {
      diameter: '49.244 km',
      distance: '4,5 tỷ km từ Mặt Trời',
      orbitalPeriod: '164,8 năm Trái Đất',
      temp: '-218°C · Gió bão 2.100 km/h',
    },
    philosophy: {
      concept: 'Thực tiễn — Tiêu chuẩn của chân lý khách quan',
      quote: 'Từ trực quan sinh động đến tư duy trừu tượng, và từ tư duy trừu tượng đến thực tiễn — đó là con đường biện chứng của sự nhận thức chân lý.',
      author: 'V.I. Lênin (Bút ký triết học)',
      analysis:
        'Sao Hải Vương là thiên thể đầu tiên được phát hiện bằng tính toán toán học thuần túy (dựa trên sự nhiễu loạn quỹ đạo Sao Thiên Vương) trước khi kính thiên văn nhìn thấy năm 1846. Sự kiện này là thắng lợi rực rỡ của năng lực nhận thức con người và khẳng định chân lý khách quan qua thực tiễn kiểm nghiệm.',
    },
  },
]
